# Generated by Django 6.0.2 on 2026-02-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills_offered',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills_wanted',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
