# Generated by Django 6.0.2 on 2026-03-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_profile_skills_profile_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='profile_pic',
        ),
    ]
