# Generated by Django 6.0.2 on 2026-03-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_is_phone_verified_profile_phone_verified_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
