# Generated by Django 6.0.2 on 2026-03-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profile_languages_connection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
