# Generated by Django 6.0.2 on 2026-03-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_course_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='course',
        ),
        migrations.RemoveField(
            model_name='note',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
