# Generated by Django 6.0.2 on 2026-03-02 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_course_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
    ]
