# Generated by Django 6.0.2 on 2026-03-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_note_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='note',
            name='uploaded_at',
        ),
    ]
