# Generated by Django 6.0.2 on 2026-03-02 21:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_user_note_uploaded_by_remove_note_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
